name: Build and Deploy to kind

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t flask-app:latest ./app
      - name: Install kind & kubectl
        uses: engineerd/setup-kind@v0.5.0
      - name: Load image into kind
        run: kind load docker-image flask-app:latest
      - name: Apply manifests
        run: kubectl apply -f manifests/
