name: CI/CD

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        app: [v1, v2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ matrix.app }}

      - name: Build Docker image for ${{ matrix.app }}
        run: |
          cd ${{ matrix.app }}/app
          docker build -t flask-configmap:${{ matrix.app }} .

      - name: Load image into kind
        run: kind load docker-image flask-configmap:${{ matrix.app }}

      - name: Deploy to kind
        run: kubectl apply -f ${{ matrix.app }}/manifests/
